name: Concatenate JS Files

on:
  push:
    branches:
      - master  # Run this workflow on pushes to the master branch.

permissions:
  contents: write  # Allows the token to push changes to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Concatenate JavaScript Files
        run: |
          mkdir -p dist
          cat \
          Javascript/EzUI/InternalSupers/StateController.js \
          Javascript/EzUI/InternalSupers/ElementController.js \
          Javascript/EzUI/DeveloperClasses/ElementNode.js \
          Javascript/EzUI/DeveloperClasses/EzUI.js \
          Javascript/EzUI/DeveloperClasses/UIElement.js \
          Javascript/TeamUp/Api/CanvasAPIMock.js \
          Javascript/TeamUp/Api/MsgBrokerMock.js \
          Javascript/TeamUp/Api/PersistenceMock.js \
          Javascript/TeamUp/Api/API.js \
          Javascript/TeamUp/GroupMember/UIElements/AssignmentGroupMember.js \
          Javascript/TeamUp/GroupMember/GroupMember.js \
          Javascript/TeamUp/Group/UIElementer/StudentGroup.js \
          Javascript/TeamUp/Group/Group.js \
          Javascript/TeamUp/Bruker/UIElementer/CollapsedState.js \
          Javascript/TeamUp/Bruker/UIElementer/ExpandedState.js \
          Javascript/TeamUp/Bruker/UIElementer/StudentUI.js \
          Javascript/TeamUp/Bruker/UIElementer/TeacherUI.js \
          Javascript/TeamUp/Bruker/Student.js \
          Javascript/TeamUp/Bruker/Underviser.js \
          Javascript/TeamUp/Program/BasicSolution.js \
          Javascript/TeamUp/TamperMonkeyMain.js \
          > dist/bundle.js  # Concatenate all files into dist/bundle.js

      - name: Commit and Push Concatenated File
        run: |
          # Set up Git configuration
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
          # Debugging: List files in the repository and the dist folder
          echo "Listing repository files:"
          ls -R # List all files in the repo for debugging
      
          echo "Listing files in dist directory:"
          ls dist/ # Ensure the bundle.js file is in dist/
      
          # Move the concatenated file to the target directory
          mv dist/bundle.js Javascript/TeamUpBundle.js  # This line fails if the path is incorrect
      
          # Debugging: Confirm that the file was moved
          echo "Files in Javascript directory:"
          ls Javascript/  # Verify that the file has been moved
      
          git add Javascript/TeamUpBundle.js
          git commit -m "Add/update concatenated JS file [skip ci]"
      
          # Authenticate with the token
          git remote set-url origin https://github-actions:${{ secrets.GH_TOKEN }}@github.com/Kaffannen/Solution.git
      
          # Push the changes
          git push origin master