name: Concatenate JS Files

on:
  push:
    branches:
      - master  # Run this workflow on pushes to the master branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Concatenate JavaScript Files
        run: |
          mkdir -p dist
          cat \
          Javascript/EzUI/InternalSupers/StateController.js \
          Javascript/EzUI/InternalSupers/ElementController.js \
          Javascript/EzUI/DeveloperClasses/ElementNode.js \
          > dist/bundle.js

      - name: Commit and Push Concatenated File
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mv dist/bundle.js javascript/TeamUp/bundle.js
          git add javascript/TeamUp/bundle.js
          git commit -m "Add/update concatenated JS file [skip ci]"
          git push origin master
